(defparameter *seconds* (* 365 (* 24 (* 60 60))))
(princ *seconds*)
(princ #\newline)
(princ (* 2 *seconds*))
(princ #\newline)
(princ (* 5 *seconds*))
(princ #\newline)
(princ (* 10 *seconds*))
(princ #\newline)

